package com.learningdashboard.backend.storage;

import java.net.URL;
import java.util.UUID;

/**
 * Everything that touches S3 (or, later, a different object store) goes
 * through this interface — pipelines and controllers never see an
 * {@code S3Client} directly. Artifacts are always uploaded by the
 * backend itself (the LLM's image bytes go straight to S3); presigned
 * URLs are for time-limited client-side *access* (viewing a generated
 * image, or later, uploading raw learning material for ingestion), not
 * for the AI-generation write path.
 */
public interface ArtifactStorage {

    /**
     * Uploads generated bytes and creates the tracking row. New
     * artifacts start with a short orphan-expiry window (see {@link
     * Artifact#markOrphanExpiry}) that's cleared once {@link
     * #attachToConcept} is called — an artifact that's never attached to
     * a saved concept (e.g. the user abandoned the job) gets cleaned up
     * automatically instead of accumulating forever.
     */
    Artifact uploadGenerated(byte[] bytes, String contentType, UUID userId, UUID generationJobId);

    /** Marks an artifact as permanently kept, once its concept (and the exact version it belongs to) is actually saved. */
    Artifact attachToConcept(UUID artifactId, UUID conceptId, UUID conceptVersionId);

    /** Time-limited GET URL, TTL from {@code PRESIGN_TTL_MINUTES}. */
    URL presignDownloadUrl(Artifact artifact);

    /** Time-limited PUT URL for future client-side uploads (e.g. learning-material ingestion). */
    URL presignUploadUrl(String keyHint, String contentType, UUID userId);
}
